### ISSUE TITLE
Melhorar o SEO

### ISSUE THREAD

**Issue by emersonlaurentino** [klzns/audiodozap#4]
- Usar o recurso de Static Site Generator do Gatsby
- Adicionar a Transcrição como descrição da página para os indexadores melhorar posicionamento do site nos resultados de busca
- Usar H1 invés de H2 no titulo da página, para sinalizar que é de fato um Título

referencias: 

https://www.searchenginejournal.com/seo-basics-to-be-successful/343811/
https://www.gatsbyjs.org/docs/add-seo-component/

**Comment by klzns** [comment]
Boa! Ja corrigi o excerpt/description.

To vendo o ponto 3.

Nao entendi o ponto 1, ele ja é estatico

**Comment by emersonlaurentino** [comment]
realmente o ponto 1 não faz sentido, é que eu tinha feito um teste anteriormente e ele mostrava como spa, estranho.

**Comment by klzns** [comment]
É um PWA, sera que nao confundiu com isso?

**Comment by emersonlaurentino** [comment]
Não, eu tinha olhado o page source e tava como spa, mas olhei agora novamente e está como esperava - melhor então.

**Comment by klzns** [comment]
Feito!
